/*
 Navicat Premium Data Transfer

 Source Server         : localhost
 Source Server Type    : MariaDB
 Source Server Version : 100420
 Source Host           : localhost:3306
 Source Schema         : perisai_api

 Target Server Type    : MariaDB
 Target Server Version : 100420
 File Encoding         : 65001

 Date: 01/07/2024 14:24:44
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for berita
-- ----------------------------
DROP TABLE IF EXISTS `berita`;
CREATE TABLE `berita`  (
  `id_berita` int(255) NOT NULL AUTO_INCREMENT,
  `nama_berita` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `kode_satker` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `facebook` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
  `website` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `instagram` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `twitter` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `tiktok` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `sippn` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `youtube` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `media_lokal` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `media_nasional` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `tgl_input` date NULL DEFAULT NULL,
  `tgl_update` date NULL DEFAULT NULL,
  PRIMARY KEY (`id_berita`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 343 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of berita
-- ----------------------------
INSERT INTO `berita` VALUES (80, 'Voluptatem Corporis', 'SAT-NTB-01', 'Nam aspernatur autem', 'https://www.myqonibeloka.us', 'Quis deserunt iste q', 'Minim eiusmod molest', 'Minus illum quia no', 'Maiores totam omnis', 'Iure ea nulla qui mi', '[\"MED-NTB-01|||Judul|||LinkLokal1\",\"MED-NTB-02|||Judul|||LinkLokal2\",\"MED-NTB-02|||Judul|||LinkLokal3\",\"MED-NTB-02|||Judul|||LinkLokal4\",\"MED-NTB-01|||Judul|||LinkLokal5\"]', '[\"MED-NTB-03|||Judul|||LinkNasional1\",\"MED-NTB-03|||Judul|||LinkNasional2\"]', '2024-06-12', '2024-06-20');
INSERT INTO `berita` VALUES (82, 'Tes Judul Humas Kanwil', 'SAT-NTB-02', 'Vero est enim minus', 'https://www.zogyquge.tv', 'Nisi amet excepturi', 'Qui velit duis arch', 'Dolore dicta commodo', 'Non unde sunt et mol', 'Quisquam quas ipsum', '[\"MED-NTB-10|||Judul1|||LinkLokal1\",\"MED-NTB-10|||Judul1|||LinkLokal2\",\"MED-NTB-10|||Judul3|||LinkLokal3\",\"MED-NTB-04|||Judul1|||LinkLokal4\"]', '[\"MED-NTB-02|||Judul1|||LinkNasional1\",\"MED-NTB-02|||Judul1|||LinkNasional2\",\"MED-NTB-01|||Judul1|||LinkNasional3\"]', '2024-06-12', '2024-06-03');
INSERT INTO `berita` VALUES (83, 'Eum nostrum exercita', 'SAT-NTB-01', 'Nam maxime numquam c', 'https://www.fowefo.co.uk', 'Quia quos reiciendis', 'Duis vitae ut nobis', 'Architecto a volupta', 'Earum rerum exceptur', 'Magnam consequuntur', '[\"MED-NTB-01|||Omnis ut exercitatio|||Link2\",\"MED-NTB-03|||Omnis ut exercitatio|||Link3\",\"MED-NTB-03|||Omnis ut exercitatio|||Link4\"]', '[\"MED-NTB-04|||Non soluta maiores e|||LinkNas1\",\"MED-NTB-01|||Non soluta maiores e|||LinkNas2\",\"MED-NTB-03|||Non soluta maiores e|||LinkNas3\"]', '2024-06-10', '2024-06-04');
INSERT INTO `berita` VALUES (84, 'Sunt nisi quidem max', 'SAT-NTB-04', 'Ea doloribus nihil o', 'https://www.foxiciwij.info', 'Ullam laboriosam qu', 'Consequat Earum ill', 'Quia pariatur Do ve', 'Hic iure ipsum ipsa', 'Delectus vitae tene', '[\"MED-NTB-03|||Nihil dolore quod of|||LinkLokal1\",\"MED-NTB-01|||Nihil dolore quod of|||LinkLokal2\",\"MED-NTB-02|||Nihil dolore quod of|||LinkLokal3\"]', '[\"MED-NTB-01|||Quos sequi reprehend|||LinkNasional1\",\"MED-NTB-04|||Quos sequi reprehend|||LinkNasional2\",\"MED-NTB-04|||Quos sequi reprehend|||LinkNasional3\"]', '2024-06-11', NULL);
INSERT INTO `berita` VALUES (85, 'Magnam quae voluptat', 'SAT-NTB-04', 'Dolores do consequat', 'https://www.weroqydo.org', 'Laudantium facere a', 'Quas eius quas persp', 'Sequi ipsam voluptat', 'Nihil nemo eum dolor', 'Sint possimus quid', '[\"MED-NTB-02|||Voluptate aliquid qu|||Link2\",\"MED-NTB-02|||Voluptate aliquid qu|||Link3\",\"MED-NTB-01|||Voluptate aliquid qu|||Link4\"]', '[\"MED-NTB-05|||Voluptate aliquid qu|||LinkNasional1\",\"MED-NTB-03|||Voluptate aliquid qu|||LinkNasional2\",\"MED-NTB-04|||Voluptate aliquid qu|||LinkNasional3\",\"MED-NTB-05|||Voluptate aliquid qu|||LinkNasional4\"]', '2024-06-11', '2024-06-05');
INSERT INTO `berita` VALUES (86, 'Magnam quae voluptat', 'SAT-NTB-05', 'Dolores do consequat', 'https://www.weroqydo.org', 'Laudantium facere a', 'Quas eius quas persp', 'Sequi ipsam voluptat', 'Nihil nemo eum dolor', 'Sint possimus quid', '[\"MED-NTB-05|||Voluptate aliquid qu|||Link1\",\"MED-NTB-02|||Voluptate aliquid qu|||Link2\",\"MED-NTB-02|||Voluptate aliquid qu|||Link3\",\"MED-NTB-01|||Voluptate aliquid qu|||Link4\"]', '[\"MED-NTB-05|||Voluptate aliquid qu|||LinkNasional1\",\"MED-NTB-03|||Voluptate aliquid qu|||LinkNasional2\",\"MED-NTB-04|||Voluptate aliquid qu|||LinkNasional3\",\"MED-NTB-05|||Voluptate aliquid qu|||LinkNasional4\"]', '2024-06-11', '2024-06-05');
INSERT INTO `berita` VALUES (87, 'Laboris voluptas cup', 'SAT-NTB-05', 'Ullamco officiis con', 'https://www.belopizyvig.info', 'Est voluptatem occa', 'Sunt expedita dolore', 'Non et et iure incid', 'Omnis eum veritatis', 'Temporibus reprehend', '[\"MED-NTB-01|||Exercitation dicta e|||Link1\",\"MED-NTB-02|||Exercitation dicta e|||Link2\",\"MED-NTB-03|||Exercitation dicta e|||Link3\"]', '[\"no media|||-|||-\"]', '2024-06-10', NULL);
INSERT INTO `berita` VALUES (88, 'Tes judul berita 13 juni 2024', 'SAT-NTB-05', 'https://www.facebook.com/?locale=id_ID', 'https://www.website.com/?locale=id_ID', 'https://www.instagram.com/?locale=id_ID', 'https://www.twitter.com/?locale=id_ID', 'https://www.tiktok.com/?locale=id_ID', 'https://www.sippn.com/?locale=id_ID', 'https://www.youtube.com/?locale=id_ID', '[\"MED-NTB-09|||Provident consectet|||Link1\",\"MED-NTB-09|||Provident consectet|||Link2\",\"MED-NTB-09|||Provident consectet|||Link3\"]', '[\"no media|||-|||-\"]', '2024-06-12', NULL);
INSERT INTO `berita` VALUES (89, 'TESTING BERITA', 'SAT-NTB-01', 'Elit quasi rerum vo', 'https://www.puxote.org', 'Voluptatibus et minu', 'Commodi in qui qui m', 'Hic sed cupidatat ve', 'Iste dicta cupiditat', 'Aut dicta amet labo', '[\"no media|||Minima officia sequi|||Link1\",\"no media|||Minima officia sequi|||Link2\",\"no media|||Minima officia sequi|||Link3\"]', '[\"no media|||Nulla ea accusamus c|||Link1\",\"no media|||Nulla ea accusamus c|||Link2\",\"no media|||Nulla ea accusamus c|||Link3\"]', '2024-06-20', '2024-06-21');
INSERT INTO `berita` VALUES (90, 'BERITA LAPAS LOBAR', 'SAT-NTB-04', 'Id modi dolorem offi', 'https://www.budafuhad.me.uk', 'Velit in architecto', 'Et elit duis est v', 'Eiusmod animi molli', 'Optio sed odio opti', 'Illum proident ab', '[\"MED-NTB-07|||Provident consectet|||Link1\",\"MED-NTB-08|||Provident consectet|||Link1\"]', '[\"MED-NTB-02|||Iure rerum dolor hic|||Link1\",\"no media|||Iure rerum dolor hic|||Link2\"]', '2024-06-24', '2024-06-21');
INSERT INTO `berita` VALUES (91, 'CEK BERITA BROY', 'SAT-NTB-01', 'Tenetur aliquip adip', 'https://www.tononilypuqax.me', 'Dolorem quam illum', 'Sit proident maxim', 'Voluptatem et cum do', 'Corrupti eos quas', 'Consectetur in nisi', '[\"no media|||Rerum voluptatem do\"]', '[\"no media|||Odio aliquam sit es\"]', '2024-06-27', '2024-06-27');
INSERT INTO `berita` VALUES (302, 'GELAR TIMPORA, KANWIL KEMENKUMHAM NTB PERKUAT PENGAWASAN ORANG ASING:', 'SAT-NTB-01', 'https://www.facebook.com/permalink.php?story_fbid=pfbid0M678Qv92tdVAjdxeZzKhHDETRncsBvqiZCuDJbmHY9FkbvQoVQJfoKLAMPXwo5Lvl&id=61560886213034', 'https://ntb.kemenkumham.go.id/berita-utama/gelar-timpora-kanwil-kemenkumham-ntb-perkuat-pengawasan-orang-asing', '-', 'https://x.com/KumhamNTB/status/1805803755511927210', '-', '-', '-', '[\"MED-NTB-01|||GELAR TIMPORA, KANWIL KEMENKUMHAM NTB PERKUAT PENGAWASAN ORANG ASING: |||| https:\\/\\/lombok.tribunnews.com\\/2024\\/06\\/26\\/gelar-timpora-kanwil-kemenkumham-ntb-perkuat-pengawasan-orang-asing\",\"MED-NTB-02|||KANWIL KEMENKUMHAM NTB PERKUAT PENGAWASAN ORANG ASING: ||| https:\\/\\/radarlombok.co.id\\/kanwil-kemenkumham-ntb-perkuat-pengawasan-orang-asing.html\"]', '[\"no media|||-|||-\"]', '2024-06-26', '2024-06-26');
INSERT INTO `berita` VALUES (303, 'KANWIL KEMENKUMHAM NTB  FASILITASI PENYUSUNAN NASKAH AKADEMIK DI SUMBAWA BARAT:', 'SAT-NTB-01', 'https://www.facebook.com/permalink.php?story_fbid=pfbid0ArYpsR9wCgtTDsxUjLTJ8iboyGubtNPBJ5v2BK8BM6Z3v7gPAJx31uovPqw7sGRdl&id=61560886213034', 'https://ntb.kemenkumham.go.id/berita-utama/kanwil-kemenkumham-ntb-fasilitasi-penyusunan-naskah-akademik-di-sumbawa-barat', '-', 'https://x.com/KumhamNTB/status/1805803971241705670', '-', '-', '-', '[\"MED-NTB-02|||KANWIL KEMENKUMHAM NTB  FASILITASI PENYUSUNAN NASKAH AKADEMIK DI SUMBAWA BARAT: ||| https:\\/\\/radarlombok.co.id\\/kanwil-kemenkumham-ntb-fasilitasi-penyusunan-naskah-akademik-di-sumbawa-barat.html\",\"MED-NTB-03|||KANWIL KEMENKUMHAM NTB  FASILITASI PENYUSUNAN NASKAH AKADEMIK DI SUMBAWA BARAT: ||| https:\\/\\/www.suarantb.com\\/2024\\/06\\/25\\/kanwil-kemenkumham-ntb-fasilitasi-penyusunan-naskah-akademik-di-sumbawa-barat\\/\",\"MED-NTB-04|||KANWIL KEMENKUMHAM NTB  FASILITASI PENYUSUNAN NASKAH AKADEMIK DI SUMBAWA BARAT: ||| https:\\/\\/lombokpost.jawapos.com\\/ntb\\/1504798268\\/kanwil-kemenkumham-ntb-fasilitasi-penyusunan-naskah-akademik-di-sumbawa-barat\"]', '[\"no media|||-|||-\"]', '2024-06-26', '2024-06-26');
INSERT INTO `berita` VALUES (304, 'KANWIL KEMENKUMHAM NTB SIAP LANJUTKAN TREN POSITIF RAIH OPINI WTP:', 'SAT-NTB-01', 'https://www.facebook.com/permalink.php?story_fbid=pfbid07NWc7iXyZGjNMH3CBYcBmAh8QfsURt16nBVLRSH3Pm5uaxK6p11qqn1Bfh4VkrsLl&id=61560886213034', 'https://ntb.kemenkumham.go.id/berita-utama/kanwil-kemenkumham-ntb-siap-lanjutkan-tren-positif-raih-opini-wtp', '-', 'https://x.com/KumhamNTB/status/1805866602682106346', '-', '-', '-', '[\"MED-NTB-08|||KANWIL KEMENKUMHAM NTB MENUJU OPINI WTP DENGAN TREN POSITIF: |||  https:\\/\\/rri.co.id\\/mataram\\/daerah\\/781641\\/kanwil-kemenkumham-ntb-menuju-opini-wtp-dengan-tren-positif\",\"MED-NTB-04|||KANWIL KEMENKUMHAM NTB SIAP LANJUTKAN TREN POSITIF RAIH OPINI WTP: ||| https:\\/\\/lombokpost.jawapos.com\\/ntb\\/1504799246\\/kanwil-kemenkumham-ntb-siap-lanjutkan-tren-positif-raih-opini-wtp\",\"MED-NTB-03|||KANWIL KEMENKUMHAM NTB SIAP LANJUTKAN TREN POSITIF RAIH OPINI WTP: ||| https:\\/\\/www.suarantb.com\\/2024\\/06\\/26\\/kanwil-kemenkumham-ntb-siap-lanjutkan-tren-positif-raih-opini-wtp\\/\",\"MED-NTB-06|||KANWIL KEMENKUMHAM NTB SIAP LANJUTKAN TREN POSITIF RAIH OPINI WTP: ||| https:\\/\\/gerbangindonesia.co.id\\/2024\\/06\\/26\\/kanwil-kemenkumham-ntb-siap-lanjutkan-tren-positif-raih-opini-wtp\\/\\/\"]', '[\"no media|||-|||-\"]', '2024-06-26', '2024-06-26');
INSERT INTO `berita` VALUES (305, 'ONE STOP SERVICE KANWIL KEMENKUMHAM NTB BERSAMA DJKI GELAR PATENT ONE STOP SERVICE:', 'SAT-NTB-01', 'https://www.facebook.com/permalink.php?story_fbid=pfbid0Ar7WmqmwKxVyMTXRH6ogybcbfLQwM49MTeBG4awJhLAE8Um3g3LMtEm4kQBErHbbl&id=61560886213034', 'https://ntb.kemenkumham.go.id/berita-utama/kanwil-kemenkumham-ntb-bersama-djki-gelar-patent-one-stop-service', '-', 'https://x.com/KumhamNTB/status/1805869612141363671', '-', '-', '-', '[\"MED-NTB-08|||KANWIL KEMENKUMHAM NTB DAN DJKI GELAR PATENT ONE STOP SERVICE: ||| https:\\/\\/rri.co.id\\/mataram\\/daerah\\/781673\\/kanwil-kemenkumham-ntb-dan-djki-gelar-patent-one-stop-service\",\"MED-NTB-08|||KANWIL NTB DAN DJKI DORONG PENDAFTARAN PATEN MELALUI LAYANAN ONE STOP SERVICE:\",\"MED-NTB-04|||KANWIL NTB DAN DJKI DORONG INVESTOR DAFTARKAN PATEN LEWAT ONE STEP SERVICE: ||| https:\\/\\/lombokpost.jawapos.com\\/ntb\\/1504799542\\/kanwil-ntb-dan-djki-dorong-inventor-daftarkan-paten-lewat-one-stop-service\",\"MED-NTB-03|||KANWIL NTB DAN DJKI DORONG INVESTOR DAFTARKAN PATEN LEWAT ONE STEP SERVICE:  |||\"]', '[\"no media|||-|||-\"]', '2024-06-26', '2024-06-26');
INSERT INTO `berita` VALUES (306, 'KANWIL KEMENKUMHAM NTB GELAR PRA REKONSILIASI LAPORAN KEUANGAN DAN BMN:', 'SAT-NTB-01', '-', '-', '-', '-', '-', '-', '-', '[\"MED-NTB-08|||KANWIL KEMENKUMHAM NTB GELAR PRA REKONSILIASI LAPORAN KEUANGAN DAN BMN: ||| https:\\/\\/rri.co.id\\/mataram\\/daerah\\/781648\\/kanwil-kemenkumham-ntb-gelar-pra-rekonsiliasi-laporan-keuangan-dan-bmn\"]', '[\"no media|||-|||-\"]', '2024-06-26', NULL);
INSERT INTO `berita` VALUES (307, 'KEMENKUMHAM NTB REKOMENDASIKAN RAPERDA BERBASIS HAM:', 'SAT-NTB-01', '-', '-', '-', '-', '-', '-', '-', '[\"MED-NTB-08|||KEMENKUMHAM NTB REKOMENDASIKAN RAPERDA BERBASIS HAM: ||| https:\\/\\/rri.co.id\\/mataram\\/daerah\\/781665\\/kemenkumham-ntb-rekomendasikan-raperda-berbasis-ham\",\"MED-NTB-03|||KEMENKUMHAM NTB REKOMENDASIKAN RAPERDA BERBASIS HAM: ||| https:\\/\\/www.suarantb.com\\/2024\\/06\\/26\\/cegah-puu-tidak-melanggar-ham-kemenkumham-ntb-rumuskan-rekomendasi-raperda-berbasis-ham\\/\"]', '[\"no media|||-|||-\"]', '2024-06-26', '2024-06-26');
INSERT INTO `berita` VALUES (308, 'KANWIL KEMENKUMHAM NTB DISEMINASI PERSEROAN PERORANGAN DAN LAYANAN APOSTILLLE KOTA BIMA:', 'SAT-NTB-01', '-', '-', '-', '-', '-', '-', '-', '[\"MED-NTB-01|||KANWIL KEMENKUMHAM NTB DISEMINASI PERSEROAN PERORANGAN DAN LAYANAN APOSTILLLE KOTA BIMA: ||| https:\\/\\/lombok.tribunnews.com\\/2024\\/06\\/26\\/kemenkumham-ntb-gelar-diseminasi-perseroan-perorangan-dan-layanan-apostille-di-kota-bima\",\"MED-NTB-02|||KANWIL KEMENKUMHAM NTB DISEMINASI PERSEROAN PERORANGAN DAN LAYANAN APOSTILLLE KOTA BIMA: ||| https:\\/\\/radarlombok.co.id\\/kanwil-kemenkumham-ntb-diseminasi-perseroan-perorangan-dan-layanan-apostille-di-kota-bima.html\"]', '[\"no media|||-|||-\"]', '2024-06-26', '2024-06-27');
INSERT INTO `berita` VALUES (322, 'Provident impedit', 'SAT-NTB-01', 'Quas ipsum ipsam ne', 'https://www.qipalysym.org', 'Proident ducimus q', 'Quia sed minim nihil', 'Nulla natus sunt la', 'Possimus animi qui', 'Et sed ut qui repreh', '[\"MED-NTB-07|||Eiusmod incidunt ul|||Link1\",\"MED-NTB-08|||Eiusmod incidunt ul|||Link2\"]', '[\"MED-NTB-05|||Quisquam eos omnis m\"]', '2024-06-28', NULL);
INSERT INTO `berita` VALUES (323, 'Et molestias ducimus', 'SAT-NTB-01', 'Amet totam fugit c', 'https://www.duhutyl.org', 'Nisi sit dolore cor', 'Qui placeat consequ', 'Corrupti cupiditate', 'Accusamus aut suscip', 'Qui exercitationem u', '[\"MED-NTB-07|||Consectetur sed mol|||Link1\",\"MED-NTB-09|||Consectetur sed mol|||Link2\"]', '[\"MED-NTB-03|||Laudantium incidunt\"]', '2024-06-28', NULL);
INSERT INTO `berita` VALUES (324, 'Aut maxime et nostru', 'SAT-NTB-01', 'Dolores laboriosam', 'https://www.hokywec.cc', 'Nihil in dolore culp', 'Aut officia dolorem', 'Ut dolore quas autem', 'In molestiae consequ', 'Veniam lorem culpa', '[\"MED-NTB-011|||Cillum fuga Sint n|||Link1\"]', '[\"MED-NTB-04|||Distinctio Vitae fu\"]', '2024-06-28', NULL);
INSERT INTO `berita` VALUES (341, 'Ut est iste dolorem', 'SAT-NTB-01', 'Alias omnis minus ve', 'https://www.pohebanega.org.au', 'Nulla reprehenderit', 'Mollit nihil ea inci', 'Minim sint atque nul', 'Rerum occaecat labor', 'Fugiat quia molesti', '[\"MED-NTB-011|||Anim incididunt ex e|||Link1\",\"MED-NTB-011|||Soluta nihil sed con|||Link2\"]', '[\"MED-NTB-10|||Rerum quasi minus co\"]', '2024-07-01', NULL);
INSERT INTO `berita` VALUES (342, 'Quibusdam dolor tene', 'SAT-NTB-01', 'Vero consequatur se', 'https://www.bonagucejajyp.us', 'Nobis dolor veritati', 'Eos saepe ab corpor', 'Dolorum labore atque', 'Dolores culpa sed e', 'Saepe vel amet sequ', '[\"MED-NTB-10|||Nam sequi saepe nece\",\"MED-NTB-02|||Optio laboriosam e\"]', '[\"no media|||Nesciunt qui enim m\"]', '2024-07-01', NULL);

SET FOREIGN_KEY_CHECKS = 1;
